### ISSUE TITLE
Minor CSS issue: images have an underline when placing a mouse above them

### ISSUE THREAD

**Issue by afiskon** [radareorg/radareorg#55]
It's especially annoying on Download page where an underline causes shifting the rest of the content below.

Screenshot: https://afiskon.ru/s/d9/ee382d9428_temp.png

**Comment by pawlos** [comment]
the problem is with the following html

```html
    <a class="reference external" href="https://github.com/radare/radare2"><img alt="linux download link" class="align-middle" src="_images/linux.png" style="width: 76.8px; height: 76.8px;"></a>
```

images should have `image-reference` set instead of `reference`. I have not idea where/how it's being set in the downloads.rst file.  Using `image-reference` has a separate rule in alabaster theme that will omit the underline.

```css
    /* Don't put an underline on images */
    a.image-reference, a.image-reference:hover {
      border-bottom: none;
    }
```
